#服务端口号&项目名称
server:
  port: 8088
  servlet:
    context-path: /chat
spring:
  mvc:
    view:
      prefix: /templates
      suffix: .html
    static-path-pattern: /**
#resources:
#    static-locations:["/templates/","/static/"]